<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Countries extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Countries_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'countries/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'countries/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'countries/index.html';
            $config['first_url'] = base_url() . 'countries/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Countries_model->total_rows($q);
        $countries = $this->Countries_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'countries_data' => $countries,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('countries/countries_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Countries_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'country_code' => $row->country_code,
		'country_name' => $row->country_name,
	    );
            $this->load->view('countries/countries_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('countries'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('countries/create_action'),
	    'id' => set_value('id'),
	    'country_code' => set_value('country_code'),
	    'country_name' => set_value('country_name'),
	);
        $this->load->view('countries/countries_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'country_code' => $this->input->post('country_code',TRUE),
		'country_name' => $this->input->post('country_name',TRUE),
	    );

            $this->Countries_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('countries'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Countries_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('countries/update_action'),
		'id' => set_value('id', $row->id),
		'country_code' => set_value('country_code', $row->country_code),
		'country_name' => set_value('country_name', $row->country_name),
	    );
            $this->load->view('countries/countries_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('countries'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'country_code' => $this->input->post('country_code',TRUE),
		'country_name' => $this->input->post('country_name',TRUE),
	    );

            $this->Countries_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('countries'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Countries_model->get_by_id($id);

        if ($row) {
            $this->Countries_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('countries'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('countries'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('country_code', 'country code', 'trim|required');
	$this->form_validation->set_rules('country_name', 'country name', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Countries.php */
/* Location: ./application/controllers/Countries.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 13:30:03 */
/* http://harviacode.com */