<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Genders extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Genders_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'genders/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'genders/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'genders/index.html';
            $config['first_url'] = base_url() . 'genders/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Genders_model->total_rows($q);
        $genders = $this->Genders_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'genders_data' => $genders,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('genders/genders_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Genders_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'gender' => $row->gender,
	    );
            $this->load->view('genders/genders_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('genders'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('genders/create_action'),
	    'id' => set_value('id'),
	    'gender' => set_value('gender'),
	);
        $this->load->view('genders/genders_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'gender' => $this->input->post('gender',TRUE),
	    );

            $this->Genders_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('genders'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Genders_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('genders/update_action'),
		'id' => set_value('id', $row->id),
		'gender' => set_value('gender', $row->gender),
	    );
            $this->load->view('genders/genders_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('genders'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'gender' => $this->input->post('gender',TRUE),
	    );

            $this->Genders_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('genders'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Genders_model->get_by_id($id);

        if ($row) {
            $this->Genders_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('genders'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('genders'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('gender', 'gender', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Genders.php */
/* Location: ./application/controllers/Genders.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 13:30:04 */
/* http://harviacode.com */