<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Locals extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Locals_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'locals/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'locals/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'locals/index.html';
            $config['first_url'] = base_url() . 'locals/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Locals_model->total_rows($q);
        $locals = $this->Locals_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'locals_data' => $locals,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('locals/locals_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Locals_model->get_by_id($id);
        if ($row) {
            $data = array(
		'local_id' => $row->local_id,
		'state_id' => $row->state_id,
		'local_name' => $row->local_name,
	    );
            $this->load->view('locals/locals_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('locals'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('locals/create_action'),
	    'local_id' => set_value('local_id'),
	    'state_id' => set_value('state_id'),
	    'local_name' => set_value('local_name'),
	);
        $this->load->view('locals/locals_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'state_id' => $this->input->post('state_id',TRUE),
		'local_name' => $this->input->post('local_name',TRUE),
	    );

            $this->Locals_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('locals'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Locals_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('locals/update_action'),
		'local_id' => set_value('local_id', $row->local_id),
		'state_id' => set_value('state_id', $row->state_id),
		'local_name' => set_value('local_name', $row->local_name),
	    );
            $this->load->view('locals/locals_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('locals'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('local_id', TRUE));
        } else {
            $data = array(
		'state_id' => $this->input->post('state_id',TRUE),
		'local_name' => $this->input->post('local_name',TRUE),
	    );

            $this->Locals_model->update($this->input->post('local_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('locals'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Locals_model->get_by_id($id);

        if ($row) {
            $this->Locals_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('locals'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('locals'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('state_id', 'state id', 'trim|required');
	$this->form_validation->set_rules('local_name', 'local name', 'trim|required');

	$this->form_validation->set_rules('local_id', 'local_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Locals.php */
/* Location: ./application/controllers/Locals.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 13:30:04 */
/* http://harviacode.com */