<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Marital_status extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Marital_status_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'marital_status/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'marital_status/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'marital_status/index.html';
            $config['first_url'] = base_url() . 'marital_status/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Marital_status_model->total_rows($q);
        $marital_status = $this->Marital_status_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'marital_status_data' => $marital_status,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('marital_status/marital_status_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Marital_status_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id' => $row->id,
		'status' => $row->status,
	    );
            $this->load->view('marital_status/marital_status_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('marital_status'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('marital_status/create_action'),
	    'id' => set_value('id'),
	    'status' => set_value('status'),
	);
        $this->load->view('marital_status/marital_status_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'status' => $this->input->post('status',TRUE),
	    );

            $this->Marital_status_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('marital_status'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Marital_status_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('marital_status/update_action'),
		'id' => set_value('id', $row->id),
		'status' => set_value('status', $row->status),
	    );
            $this->load->view('marital_status/marital_status_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('marital_status'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'status' => $this->input->post('status',TRUE),
	    );

            $this->Marital_status_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('marital_status'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Marital_status_model->get_by_id($id);

        if ($row) {
            $this->Marital_status_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('marital_status'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('marital_status'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('status', 'status', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Marital_status.php */
/* Location: ./application/controllers/Marital_status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 13:30:04 */
/* http://harviacode.com */