<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class States extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('States_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'states/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'states/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'states/index.html';
            $config['first_url'] = base_url() . 'states/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->States_model->total_rows($q);
        $states = $this->States_model->get_limit_data($config['per_page'], $start, $q);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'states_data' => $states,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('states/states_list', $data);
    }

    public function read($id) 
    {
        $row = $this->States_model->get_by_id($id);
        if ($row) {
            $data = array(
		'state_id' => $row->state_id,
		'name' => $row->name,
	    );
            $this->load->view('states/states_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('states'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('states/create_action'),
	    'state_id' => set_value('state_id'),
	    'name' => set_value('name'),
	);
        $this->load->view('states/states_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
	    );

            $this->States_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('states'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->States_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('states/update_action'),
		'state_id' => set_value('state_id', $row->state_id),
		'name' => set_value('name', $row->name),
	    );
            $this->load->view('states/states_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('states'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('state_id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
	    );

            $this->States_model->update($this->input->post('state_id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('states'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->States_model->get_by_id($id);

        if ($row) {
            $this->States_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('states'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('states'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');

	$this->form_validation->set_rules('state_id', 'state_id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file States.php */
/* Location: ./application/controllers/States.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-04-08 13:30:08 */
/* http://harviacode.com */